project 'ShakedIn.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShakedIn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShakedIn

end

target 'ShakedIn WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShakedIn WatchKit App

end

target 'ShakedIn WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShakedIn WatchKit Extension
  pod 'Alamofire'
end
